export const iphoneTable = [
  {
    "id": 1,
    "Pname": "apple iphone 15 pro max 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+15+pro+max+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 2,
    "Pname": "apple iphone 15 pro max 512 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+15+pro+max+-+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 3,
    "Pname": "apple iphone 15 pro max 1tb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+15+pro+max+-+1tb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 4,
    "Pname": "apple iphone 15 pro 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+15+pro+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 5,
    "Pname": "apple iphone 15 pro 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+15+pro+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 7,
    "Pname": "apple iphone 15 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+15+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 8,
    "Pname": "apple iphone 14 pro max 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+Max+-+128GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 9,
    "Pname": "apple iphone 14 pro max 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+Max+(Dual+Sim)+-+256GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 10,
    "Pname": "apple iphone 14 pro max 512 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+Max+-+512GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 11,
    "Pname": "apple iphone 14 pro max 1tb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+Max+-+1TB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 12,
    "Pname": "apple iphone 14 pro 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+-+128GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 13,
    "Pname": "apple iphone 14 pro 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+-+256GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 14,
    "Pname": "apple iphone 14 pro 512 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+-+512GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 15,
    "Pname": "apple iphone 14 pro 1 tb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Pro+-+1TB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 16,
    "Pname": "Apple IPhone 14 Plus 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Plus+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 17,
    "Pname": "Apple IPhone 14 Plus 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+14+Plus+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 18,
    "Pname": "apple iphone 13 pro max 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+pro+max+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 19,
    "Pname": "apple iphone 13 pro max 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+pro+max+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 20,
    "Pname": "apple iphone 13 pro max 512 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+pro+max+-+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 21,
    "Pname": "apple iphone 13 pro max 1 tb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+pro+max+-+1tb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 22,
    "Pname": "apple iphone 13 pro 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+pro+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 23,
    "Pname": "apple iphone 13 pro 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+pro+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 24,
    "Pname": "apple iphone 13 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 25,
    "Pname": "apple iphone 13 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 26,
    "Pname": "apple iphone 13 mini 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+13+mini+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 27,
    "Pname": "apple iphone 12 pro max 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+iPhone+12+Pro+Max+-+Unlocked+(Used)+-+12Bgb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 28,
    "Pname": "apple iphone 12 pro max 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+iPhone+12+Pro+Max+-+Unlocked+(Used)+-+256GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 29,
    "Pname": "apple iphone 12 pro max 512 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+12+pro+max+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 30,
    "Pname": "apple iphone 12 pro 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+12+pro+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 31,
    "Pname": "apple iphone 12 pro 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+12+pro+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 32,
    "Pname": "apple iphone 12 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+12+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 33,
    "Pname": "apple iphone 12 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+12+-+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 34,
    "Pname": "apple iphone 11 pro max 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+11+pro+max+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 35,
    "Pname": "apple iphone 11 pro max 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+11+pro+max+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 36,
    "Pname": "apple IPhone 11 Pro 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+IPhone+11+Pro+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 37,
    "Pname": "Apple IPhone 11 Pro  64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+11+Pro+-+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 38,
    "Pname": "Apple IPhone 11 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+11+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 39,
    "Pname": "Apple IPhone 11 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+11+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 40,
    "Pname": "Apple IPhone 11 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+11+-+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 41,
    "Pname": "apple iphone xs max 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+xs+max++-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 42,
    "Pname": "apple iphone xs max 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+xs+max+-+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 43,
    "Pname": "apple iphone xr 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+xr+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 44,
    "Pname": "apple iphone xr 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+xr+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 45,
    "Pname": "apple iphone xs 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+xs+-+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 46,
    "Pname": "apple iphone xs 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=apple+iphone+xs+-+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 47,
    "Pname": "Apple IPhone X 64 GB",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+X+-+64GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 48,
    "Pname": "Apple IPhone X 256 GB",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+X+-++256GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 49,
    "Pname": "Apple IPhone 8 plus 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+8+plus+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 50,
    "Pname": "Apple IPhone 8 plus 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+8+plus+-+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 51,
    "Pname": "Apple IPhone 8 64 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+8+-+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 52,
    "Pname": "Apple IPhone 8 256 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+8+-+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 53,
    "Pname": "Apple IPhone 7 plus 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+7+plus+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 54,
    "Pname": "Apple IPhone 7 plus 32 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+7+plus+32gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 55,
    "Pname": "Apple IPhone 7 128 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+7+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 56,
    "Pname": "Apple IPhone 7 32 gb",
    "Link": "https://obiwezy.com/catalogsearch/result/?q=Apple+IPhone+7+32gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  }
]