export const samsungTable = [
  {
    "id": 1,
    "Pname": "samsung galaxy z fold 5 1 tb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold+5+1tb",
    "H1": "2,913,000",
    "H2": "0",
    "H3": "0",
    "L1": "2,913,000",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 2,
    "Pname": "samsung galaxy z fold 5 512 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold+5+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 3,
    "Pname": "samsung galaxy z fold 5 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold+5+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 4,
    "Pname": "samsung galaxy z fold4 512 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold4+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 5,
    "Pname": "samsung galaxy z fold4 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold4+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 6,
    "Pname": "samsung galaxy z fold3 512 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold3+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 7,
    "Pname": "samsung galaxy z fold3 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold3+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 8,
    "Pname": "samsung galaxy z fold 2 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+fold+2+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 9,
    "Pname": "samsung galaxy s23 ultra 512 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s23+ultra+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 10,
    "Pname": "samsung galaxy s23 ultra 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s23+ultra+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 11,
    "Pname": "samsung galaxy s22 ultra 512 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s22+ultra+512gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 12,
    "Pname": "samsung galaxy s22 ultra 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s22+ultra+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 13,
    "Pname": "samsung galaxy s22 ultra 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s22+ultra+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 14,
    "Pname": "Samsung Galaxy S22+ 5G 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+S22++5G+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 15,
    "Pname": "samsung galaxy s22+ 5G 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s22++5G+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 16,
    "Pname": "samsung galaxy s21 ultra 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s21+ultra+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 17,
    "Pname": "samsung galaxy s21 ultra 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s21+ultra+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 18,
    "Pname": "samsung galaxy s21+ 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s21++256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 19,
    "Pname": "samsung galaxy s21+ 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s21++128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 20,
    "Pname": "samsung galaxy s20 ultra 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s20+ultra+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 21,
    "Pname": "samsung galaxy s20 ultra 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s20+ultra+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 22,
    "Pname": "samsung galaxy s20+ 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s20++256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 23,
    "Pname": "samsung galaxy s20+ 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s20++128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 24,
    "Pname": "Samsung Galaxy S10 5G 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+S10+5G+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 25,
    "Pname": "Samsung Galaxy S10 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+S10+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 26,
    "Pname": "Samsung Galaxy S10 plus 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+S10+plus+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 27,
    "Pname": "Samsung Galaxy S9 64 GB",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+S9+64GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 28,
    "Pname": "Samsung Galaxy S8 plus 64 GB",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+S8+plus+64GBsamsung+galaxy+s8+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 29,
    "Pname": "samsung galaxy s8 64 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+s7+edge+32gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 30,
    "Pname": "samsung galaxy s7 edge 32 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+flip+5+512gb",
    "H1": "1,582,000",
    "H2": "0",
    "H3": "0",
    "L1": "1,582,000",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 31,
    "Pname": "samsung galaxy z flip 5 512 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+flip+5+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 32,
    "Pname": "samsung galaxy z flip 5 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+flip4+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 33,
    "Pname": "samsung galaxy z flip4 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+flip+3+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 34,
    "Pname": "samsung galaxy z flip 3 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+z+flip+3+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 35,
    "Pname": "samsung galaxy z flip 3 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+note+20+ultra+5g+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 36,
    "Pname": "samsung galaxy note 20 ultra 5g 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+note+20+ultra+5g+128+gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 37,
    "Pname": "samsung galaxy note 20 ultra 5g 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+note10+plus+5g+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 38,
    "Pname": "samsung galaxy note10 plus 5g 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+note10+plus+5g+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 39,
    "Pname": "samsung galaxy note10 plus 5g 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+note+10+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 40,
    "Pname": "samsung galaxy note 10 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+note+9+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 41,
    "Pname": "samsung galaxy note 9 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+note+8+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 42,
    "Pname": "samsung galaxy note 8 64 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+a74+5g+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 43,
    "Pname": "samsung galaxy a74 5g 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+a74+5g+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 44,
    "Pname": "samsung galaxy a74 5g 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+a54+5g+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 45,
    "Pname": "samsung galaxy a54 5g 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+a54+5g+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 46,
    "Pname": "samsung galaxy a54 5g 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A34+5G+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 47,
    "Pname": "Samsung Galaxy A34 5G 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A34+5G+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 48,
    "Pname": "Samsung Galaxy A34 5G 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A14+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 49,
    "Pname": "Samsung Galaxy A14 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A14+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 50,
    "Pname": "Samsung Galaxy A14 64 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A04s+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 51,
    "Pname": "Samsung Galaxy A04s 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+a04s+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 52,
    "Pname": "samsung galaxy a04s 64 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A73+5G+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 53,
    "Pname": "Samsung Galaxy A73 5G 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A73+5G+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 54,
    "Pname": "Samsung Galaxy A73 5G 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A53+5G+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 55,
    "Pname": "Samsung Galaxy A53 5G 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A53+5G+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 56,
    "Pname": "Samsung Galaxy A53 5G 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A33+5G+256gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 57,
    "Pname": "Samsung Galaxy A33 5G 256 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A33+5G+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 58,
    "Pname": "Samsung Galaxy A33 5G 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+GALAXY+A23+128gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 59,
    "Pname": "Samsung GALAXY A23 128 gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A13+5G+128GB",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 60,
    "Pname": "Samsung Galaxy A13 5G 128 GB",
    "Link": "https://slot.ng/catalogsearch/result/?q=Samsung+Galaxy+A13+64gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 61,
    "Pname": "Samsung Galaxy A13 64gb",
    "Link": "https://slot.ng/catalogsearch/result/?q=samsung+galaxy+a03+core+32gb",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  }
]