export const tabletTable = [
  {
    "id": 1,
    "Pname": "IPAD 10TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+10TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 2,
    "Pname": "IPAD 5TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+5TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 3,
    "Pname": "IPAD 6TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+6TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 4,
    "Pname": "IPAD 9TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+9TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 5,
    "Pname": "IPAD AIR 2ND GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+AIR+2ND+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 6,
    "Pname": "IPAD AIR 4TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+AIR+4TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 7,
    "Pname": "IPAD AIR 5TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+AIR+5TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 8,
    "Pname": "IPAD MINI 4TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+MINI+4TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 9,
    "Pname": "IPAD MINI 6",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+MINI+6",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 10,
    "Pname": "IPAD PRO 3RD GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+PRO+3RD+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 11,
    "Pname": "IPAD PRO 4TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+PRO+4TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 12,
    "Pname": "IPAD PRO 5TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+PRO+5TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 13,
    "Pname": "IPAD PRO 6TH GEN",
    "Link": "https://slot.ng/catalogsearch/result/?q=IPAD+PRO+6TH+GEN",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 14,
    "Pname": "SAMSUNG TAB A7 LITE",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+A7+LITE",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 15,
    "Pname": "SAMSUNG TAB A8",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+A8+tablet",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 16,
    "Pname": "SAMSUNG TAB S6 LITE",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+S6+LITE",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 17,
    "Pname": "SAMSUNG TAB S7 FE",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+S7+FE",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 18,
    "Pname": "SAMSUNG TAB S8",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+S8",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 19,
    "Pname": "SAMSUNG TAB S8 PLUS",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+S8+PLUS",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 20,
    "Pname": "SAMSUNG TAB S8 ULTRA",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+S8+ULTRA",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 21,
    "Pname": "SAMSUNG TAB S9 5G",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+S9+5G",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 22,
    "Pname": "SAMSUNG TAB S9 ULTRA 5G",
    "Link": "https://slot.ng/catalogsearch/result/?q=SAMSUNG+TAB+S9+ULTRA+5G",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 23,
    "Pname": "NOKIA T10",
    "Link": "https://slot.ng/catalogsearch/result/?q=NOKIA+T10+tablet",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 24,
    "Pname": "NOKIA T20",
    "Link": "https://slot.ng/catalogsearch/result/?q=NOKIA+T20+tablet",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 25,
    "Pname": "NOKIA T21",
    "Link": "https://slot.ng/catalogsearch/result/?q=NOKIA+T21+tablet",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 26,
    "Pname": "AMAZON FIRE HD 10 PRO",
    "Link": "https://slot.ng/catalogsearch/result/?q=AMAZON+FIRE+HD+10+PRO+tablet",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 27,
    "Pname": "AMAZON FIRE HD 8 PRO",
    "Link": "https://slot.ng/catalogsearch/result/?q=AMAZON+FIRE+HD+8+PRO+tablet",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  },
  {
    "id": 28,
    "Pname": "BEBE Kids Tab B88 5G",
    "Link": "https://slot.ng/catalogsearch/result/?q=BEBE+Kids+Tab+B88+5G+tablet",
    "H1": "0",
    "H2": "0",
    "H3": "0",
    "L1": "0",
    "L2": "0",
    "L3": "0"
  }
]